method: bayes
metric:
  goal: minimize
  name: LoRA_MSE
parameters:
  batch_size:
    value: 16
  data_selection_method:
    values:
      - target_alignment
      - random
      - clustering
  epochs:
    values:
      - 10
      - 12
  experiments:
    value: lora
  lr_lora:
    distribution: log_uniform
    max: 5e-05
    min: 1e-06
  model_name:
    values:
      - ibm/MoLFormer-XL-both-10pct
      - task1_best_model.pt
  patience:
    values:
      - 3
      - 5
  selection_percent:
    distribution: uniform
    max: 0.5
    min: 0.3
program: ./task3.py